### ISSUE TITLE
一个简单的疑问？

### ISSUE THREAD

**Issue by codebuks** [surmon-china/surmon.me.native#1]
import .. from 后面的@app是啥意思，什么语法？

**Comment by surmon-china** [comment]
rn项目内置有类似webpack的文件系统，在对应的文件夹下以package.json文件为基准，配置好文件夹别名，则可以直接使用，如：https://github.com/surmon-china/surmon.me.native/blob/master/src/package.json

**Comment by codebuks** [comment]
明白，官方有文档吗，为啥我搜不到这方面的内容，可否提供一些详细的资料，多谢~

**Comment by surmon-china** [comment]
我也没找到，但在stackoverflow有答案

**Comment by surmon-china** [comment]
- http://stackoverflow.com/questions/30040534/local-require-paths-for-react-native
- https://github.com/facebook/react-native/issues/3099
