### ISSUE TITLE
 ":CFBundleIdentifier", Does Not Exist

### ISSUE THREAD

**Issue by Amuxiaomu** [surmon-china/surmon.me.native#2]
** BUILD FAILED **

The following commands produced analyzer issues:
	Analyze Base/RCTJavaScriptLoader.mm

	Analyze Modules/RCTRedBox.m
(2 commands with analyzer issues)

The following build commands failed:
	Ld build/Build/Products/Debug-iphonesimulator/blogApp.app/blogApp normal x86_64
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/blogApp.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
Failed to install the requested application
The bundle identifier of the application could not be determined.
Ensure that the application's Info.plist contains a value for CFBundleIdentifier.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/blogApp.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

**Comment by surmon-china** [comment]
最新版问题均已解决，可以升级啦
