### ISSUE TITLE
react-native run-ios 跑不起来

### ISSUE THREAD

**Issue by hermitcrabcai** [surmon-china/surmon.me.native#4]
![image](https://user-images.githubusercontent.com/26593656/34239677-df8b2ea8-e643-11e7-9ec0-47e875fe55a8.png)
![image](https://user-images.githubusercontent.com/26593656/34239682-e51ccd54-e643-11e7-849b-a9106e5e373d.png)

**Comment by surmon-china** [comment]
最新版问题均已解决，可以升级啦
