### ISSUE TITLE
run-ios失败

### ISSUE THREAD

**Issue by cucmeliu** [surmon-china/surmon.me.native#5]
ld: library not found for -lRNDeviceInfo
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **

The following build commands failed:
	Ld build/Build/Products/Debug-iphonesimulator/blogApp.app/blogApp normal x86_64
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/blogApp.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
Failed to install the requested application
The bundle identifier of the application could not be determined.
Ensure that the application's Info.plist contains a value for CFBundleIdentifier.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/blogApp.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

**Comment by hobo214** [comment]
我也是碰到这样的问题，楼主解决了吗

**Comment by surmon-china** [comment]
最新版问题均已解决，可以升级啦
