### ISSUE TITLE
丑

### ISSUE THREAD

**Issue by lzfee0227** [surmon-china/surmon.me.native#8]
请把标题下的白边去掉 蟹🦀️
搞个半透明渐变不好么

**Comment by surmon-china** [comment]
mmp

**Comment by rorschach214** [comment]
清新脱俗的iss？？

**Comment by 5201314999** [comment]
项目启动是否给个完整的流程说明 。 yarn install,  react-native run-android build failed。

**Comment by surmon-china** [comment]
@5201314999 https://github.com/surmon-china/surmon.me.native#%E5%BC%80%E5%A7%8B%E5%BC%80%E5%8F%91

**Comment by 5201314999** [comment]
我自己的问题，local.properties 有点问题，没启动成功。

**Comment by 5201314999** [comment]
集成typescript 之后我看你没tsc 编译，我自己新建的项目 index.tsx 会报@app/ 模块找不到。但是执行tsc 又没生成dist 文件夹。
